# 开发环境配置文件

# 基本的Web服务配置
server:
  port: 8888

# MySQL驱动的配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/m_api?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 101807
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# MyBatis-Plus相关配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.pandaer.server.modules
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
